//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class alunos_cadastro_automatico_det
    {
        public int id_alunos_cadastro_automatico_det { get; set; }
        public string nome { get; set; }
        public string cpf { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_envio_email { get; set; }
        public string obs { get; set; }
        public Nullable<int> id_cadastro_automatico { get; set; }
        public Nullable<decimal> idaluno { get; set; }
    
        public virtual alunos alunos { get; set; }
        public virtual alunos_cadastro_automatico alunos_cadastro_automatico { get; set; }
    }
}
