//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class areas_concentracao_disciplinas
    {
        public int id_area_concentracao { get; set; }
        public decimal id_disciplina { get; set; }
        public bool obrigatoria { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
    
        public virtual areas_concentracao areas_concentracao { get; set; }
        public virtual disciplinas disciplinas { get; set; }
    }
}
