//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class areas_concentracao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public areas_concentracao()
        {
            this.areas_concentracao_coordenadores = new HashSet<areas_concentracao_coordenadores>();
            this.areas_concentracao_disciplinas = new HashSet<areas_concentracao_disciplinas>();
            this.disciplinas = new HashSet<disciplinas>();
            this.matricula_turma = new HashSet<matricula_turma>();
        }
    
        public int id_area_concentracao { get; set; }
        public int id_curso { get; set; }
        public string nome { get; set; }
        public Nullable<int> num_eletivas { get; set; }
        public Nullable<bool> disponivel { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<areas_concentracao_coordenadores> areas_concentracao_coordenadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<areas_concentracao_disciplinas> areas_concentracao_disciplinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<disciplinas> disciplinas { get; set; }
        public virtual cursos cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula_turma> matricula_turma { get; set; }
    }
}
