//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class banca_dissertacao_obs
    {
        public int id_banca_dissertacao_obs { get; set; }
        public Nullable<System.DateTime> dataObs { get; set; }
        public string observacao { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_banca_dissertacao { get; set; }
    
        public virtual banca_dissertacao banca_dissertacao { get; set; }
    }
}
