//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class banca_dissertacao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banca_dissertacao()
        {
            this.banca_dissertacao_obs = new HashSet<banca_dissertacao_obs>();
        }
    
        public decimal id_banca { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
        public string palavras_chave { get; set; }
        public string resumo { get; set; }
        public Nullable<int> visitas { get; set; }
        public Nullable<int> downloads { get; set; }
        public string arquivo { get; set; }
        public Nullable<int> ano { get; set; }
        public string cod_ipt { get; set; }
        public string palavras_chavePreview { get; set; }
        public string resumoPreview { get; set; }
        public string arquivoPreview { get; set; }
        public string cod_iptPreview { get; set; }
        public Nullable<System.DateTime> data_aprovacao { get; set; }
        public Nullable<System.DateTime> data_reprovacao { get; set; }
        public Nullable<short> statusAprovacao { get; set; }
        public string usuarioAprovacao { get; set; }
        public int id_banca_dissertacao { get; set; }
        public Nullable<int> id_tipo_dissertacao { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banca_dissertacao_obs> banca_dissertacao_obs { get; set; }
        public virtual tipo_dissertacao tipo_dissertacao { get; set; }
        public virtual banca banca { get; set; }
    }
}
