//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class banca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public banca()
        {
            this.banca_professores = new HashSet<banca_professores>();
            this.banca_dissertacao = new HashSet<banca_dissertacao>();
        }
    
        public decimal id_banca { get; set; }
        public int id_matricula_turma { get; set; }
        public string tipo_banca { get; set; }
        public Nullable<System.DateTime> horario { get; set; }
        public string observacao { get; set; }
        public string resultado { get; set; }
        public string titulo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> data_entrega_trabalho { get; set; }
        public string portaria_mec { get; set; }
        public Nullable<System.DateTime> data_portaria_mec { get; set; }
        public Nullable<System.DateTime> data_diario_oficial { get; set; }
        public Nullable<short> remoto { get; set; }
    
        public virtual matricula_turma matricula_turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banca_professores> banca_professores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banca_dissertacao> banca_dissertacao { get; set; }
    }
}
