//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificados
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public certificados()
        {
            this.certificados_participantes = new HashSet<certificados_participantes>();
        }
    
        public int id_certificado { get; set; }
        public string evento { get; set; }
        public string campo1a { get; set; }
        public string campo2a { get; set; }
        public string campo3a { get; set; }
        public string campo3b { get; set; }
        public string campo3c { get; set; }
        public string campo3d { get; set; }
        public string assinatura1_nome { get; set; }
        public string assinatura1_cargo { get; set; }
        public string assinatura1_imagem { get; set; }
        public string assinatura2_nome { get; set; }
        public string assinatura2_cargo { get; set; }
        public string assinatura2_imagem { get; set; }
        public Nullable<System.DateTime> data_evento { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
        public Nullable<int> situacao { get; set; }
        public Nullable<int> numero_seq_inicial { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<short> tipo_certificado { get; set; }
        public string obs_folha2 { get; set; }
        public Nullable<int> id_certificado_tipo_curso { get; set; }
        public string informacao_adicional { get; set; }
        public Nullable<short> palestrante { get; set; }
    
        public virtual certificado_tipo_curso certificado_tipo_curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<certificados_participantes> certificados_participantes { get; set; }
    }
}
