//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificados_participantes
    {
        public int id_certificado_participante { get; set; }
        public string nome { get; set; }
        public string interno_externo { get; set; }
        public Nullable<int> id_certificado { get; set; }
        public Nullable<System.DateTime> data_importacao { get; set; }
        public string usuario { get; set; }
        public Nullable<int> numero_seq { get; set; }
        public string arquivo_pdf { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> data_envio_email { get; set; }
        public string senha { get; set; }
        public Nullable<System.DateTime> data_download { get; set; }
        public string chave_participante { get; set; }
    
        public virtual certificados certificados { get; set; }
    }
}
