//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_valor_coordenacao
    {
        public int id_curso_valor_coordenacao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public Nullable<int> id_curso { get; set; }
        public Nullable<int> id_tipo_coordenador { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
    
        public virtual cursos cursos { get; set; }
        public virtual curso_tipo_coordenador curso_tipo_coordenador { get; set; }
    }
}
