//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class curso_valor_orientacao
    {
        public int id_curso { get; set; }
        public int id_forma_recebimento { get; set; }
        public decimal valor_qualificacao { get; set; }
        public decimal valor_defesa { get; set; }
    
        public virtual cursos cursos { get; set; }
    }
}
