//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class datas_aulas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public datas_aulas()
        {
            this.presenca_professor = new HashSet<presenca_professor>();
            this.presenca = new HashSet<presenca>();
            this.datas_aulas_professor = new HashSet<datas_aulas_professor>();
        }
    
        public decimal id_aula { get; set; }
        public decimal id_oferecimento { get; set; }
        public decimal id_sala_aula { get; set; }
        public Nullable<System.DateTime> data_aula { get; set; }
        public Nullable<System.DateTime> hora_inicio { get; set; }
        public Nullable<System.DateTime> hora_fim { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string usuario { get; set; }
    
        public virtual salas_aula salas_aula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presenca_professor> presenca_professor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<presenca> presenca { get; set; }
        public virtual oferecimentos oferecimentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<datas_aulas_professor> datas_aulas_professor { get; set; }
    }
}
