//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentos_academicos_obs
    {
        public int id_documentos_academicos_obs { get; set; }
        public Nullable<System.DateTime> DataObs { get; set; }
        public string Observacao { get; set; }
        public string usuario { get; set; }
        public Nullable<int> id_documentos_academicos { get; set; }
    
        public virtual documentos_academicos documentos_academicos { get; set; }
    }
}
