//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class forma_recebimento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public forma_recebimento()
        {
            this.curso_valor_hora_aula = new HashSet<curso_valor_hora_aula>();
            this.professores_forma_recebimento = new HashSet<professores_forma_recebimento>();
            this.professores_forma_recebimento1 = new HashSet<professores_forma_recebimento>();
            this.professores_forma_recebimento2 = new HashSet<professores_forma_recebimento>();
            this.professores = new HashSet<professores>();
        }
    
        public int id_forma_recebimento { get; set; }
        public string nome { get; set; }
        public bool valor_fixo { get; set; }
        public bool horas_aula { get; set; }
        public bool orientacao { get; set; }
        public bool banca { get; set; }
        public Nullable<int> ordem { get; set; }
        public Nullable<decimal> valor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<curso_valor_hora_aula> curso_valor_hora_aula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professores_forma_recebimento> professores_forma_recebimento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professores_forma_recebimento> professores_forma_recebimento1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professores_forma_recebimento> professores_forma_recebimento2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professores> professores { get; set; }
    }
}
