//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class fornecedores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public fornecedores()
        {
            this.professores_forma_recebimento = new HashSet<professores_forma_recebimento>();
        }
    
        public int id_fornecedor { get; set; }
        public string nome { get; set; }
        public string cnpj { get; set; }
        public string inscricao_estadual { get; set; }
        public string logradouro_end { get; set; }
        public string numero_end { get; set; }
        public string comp_end { get; set; }
        public string bairro_end { get; set; }
        public string cidade_end { get; set; }
        public string uf_end { get; set; }
        public string cep_end { get; set; }
        public string nome_contato { get; set; }
        public string cargo { get; set; }
        public string tel_contato { get; set; }
        public string fax_contato { get; set; }
        public string cel_contato { get; set; }
        public string email_contato { get; set; }
        public string numero_banco { get; set; }
        public string nome_banco { get; set; }
        public string agencia_numero { get; set; }
        public string conta_numero { get; set; }
        public string endereco_agencia { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professores_forma_recebimento> professores_forma_recebimento { get; set; }
    }
}
