//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class inadimplentes
    {
        public decimal id_aluno { get; set; }
        public System.DateTime data { get; set; }
        public string usuario { get; set; }
    
        public virtual alunos alunos { get; set; }
    }
}
