//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class matricula_turma
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matricula_turma()
        {
            this.alunos_arquivos = new HashSet<alunos_arquivos>();
            this.historico_matricula_turma = new HashSet<historico_matricula_turma>();
            this.matricula_turma_orientacao = new HashSet<matricula_turma_orientacao>();
            this.prorrogacao = new HashSet<prorrogacao>();
            this.fichas_inscricao = new HashSet<fichas_inscricao>();
            this.banca = new HashSet<banca>();
        }
    
        public int id_matricula_turma { get; set; }
        public decimal id_turma { get; set; }
        public decimal id_aluno { get; set; }
        public Nullable<int> id_area_concentracao { get; set; }
        public Nullable<System.DateTime> data_termino { get; set; }
        public System.DateTime data_cadastro { get; set; }
        public System.DateTime data_alteracao { get; set; }
        public string usuario { get; set; }
        public string situacao { get; set; }
        public Nullable<System.DateTime> data_artigo { get; set; }
        public string nome_artigo { get; set; }
        public string orientador_artigo { get; set; }
        public Nullable<System.DateTime> data_aprovacao_artigo { get; set; }
    
        public virtual alunos alunos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alunos_arquivos> alunos_arquivos { get; set; }
        public virtual areas_concentracao areas_concentracao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historico_matricula_turma> historico_matricula_turma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula_turma_orientacao> matricula_turma_orientacao { get; set; }
        public virtual turmas turmas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prorrogacao> prorrogacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fichas_inscricao> fichas_inscricao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<banca> banca { get; set; }
    }
}
