//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class notas
    {
        public int id_nota { get; set; }
        public decimal id_oferecimento { get; set; }
        public decimal id_aluno { get; set; }
        public string conceito { get; set; }
        public string autorizado { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public string usuario { get; set; }
    
        public virtual conceitos_de_aprovacao conceitos_de_aprovacao { get; set; }
        public virtual oferecimentos oferecimentos { get; set; }
        public virtual alunos alunos { get; set; }
    }
}
