//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class oferecimentos_professores
    {
        public decimal id_oferecimento { get; set; }
        public decimal id_professor { get; set; }
        public string tipo_professor { get; set; }
        public Nullable<bool> responsavel { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
    
        public virtual oferecimentos oferecimentos { get; set; }
        public virtual professores professores { get; set; }
    }
}
