//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class professor_solicitacao_pagamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public professor_solicitacao_pagamento()
        {
            this.professor_solicitacao_plano = new HashSet<professor_solicitacao_plano>();
        }
    
        public int id_solicitacao { get; set; }
        public Nullable<decimal> id_professorOld { get; set; }
        public System.DateTime data_solicitacao { get; set; }
        public decimal valor { get; set; }
        public Nullable<System.DateTime> data_email { get; set; }
        public string nota_fiscal { get; set; }
        public Nullable<System.DateTime> data_recebimento { get; set; }
        public Nullable<System.DateTime> data_pagamento { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<professor_solicitacao_plano> professor_solicitacao_plano { get; set; }
        public virtual professores professores { get; set; }
    }
}
