//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class refTran
    {
        public string id_refTran { get; set; }
        public Nullable<System.DateTime> DataGetGemini { get; set; }
        public Nullable<System.DateTime> DataUtilizacao { get; set; }
        public Nullable<int> id_boleto { get; set; }
        public string Solicitante { get; set; }
    
        public virtual boletos boletos { get; set; }
    }
}
