//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_reuniao_cpg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tipo_reuniao_cpg()
        {
            this.prorrogacao = new HashSet<prorrogacao>();
        }
    
        public int id_tipo_reuniao_cpg { get; set; }
        public string tipo_reuniao_cpg1 { get; set; }
        public Nullable<short> ordem { get; set; }
        public Nullable<short> status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<prorrogacao> prorrogacao { get; set; }
    }
}
