//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class turmas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public turmas()
        {
            this.matricula = new HashSet<matricula>();
            this.matricula_oferecimento = new HashSet<matricula_oferecimento>();
            this.turmas_coordenadores = new HashSet<turmas_coordenadores>();
            this.turmas_disciplinas = new HashSet<turmas_disciplinas>();
            this.matricula_turma = new HashSet<matricula_turma>();
        }
    
        public decimal id_turma { get; set; }
        public bool ativo { get; set; }
        public string cod_turma { get; set; }
        public string quadrimestre { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_fim { get; set; }
        public int id_curso { get; set; }
        public Nullable<int> carga_horaria { get; set; }
        public string observacao { get; set; }
        public string portaria_mec { get; set; }
        public Nullable<System.DateTime> data_portaria_mec { get; set; }
        public Nullable<System.DateTime> data_diario_oficial { get; set; }
        public string conceito_capes { get; set; }
        public string numero_capes { get; set; }
        public Nullable<int> creditos { get; set; }
        public Nullable<int> num_max_disciplinas { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> data_cadastro { get; set; }
        public Nullable<System.DateTime> data_alteracao { get; set; }
        public string usuario { get; set; }
        public Nullable<System.DateTime> data_limite_matricula { get; set; }
    
        public virtual cursos cursos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula> matricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula_oferecimento> matricula_oferecimento { get; set; }
        public virtual quadrimestres quadrimestres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turmas_coordenadores> turmas_coordenadores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turmas_disciplinas> turmas_disciplinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<matricula_turma> matricula_turma { get; set; }
    }
}
