//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SERPI.Dominio_C
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_historico
    {
        public decimal idaluno { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string cidade_nasc { get; set; }
        public string pais_nasc { get; set; }
        public string numero_documento { get; set; }
        public string orgao_expedidor { get; set; }
        public string cod_turma { get; set; }
        public Nullable<System.DateTime> data_inicio { get; set; }
        public Nullable<System.DateTime> data_portaria_mec { get; set; }
        public string portaria_mec { get; set; }
        public Nullable<System.DateTime> data_diario_oficial { get; set; }
        public string nome_area_concentracao { get; set; }
        public decimal id_turma { get; set; }
        public string Resultado_Proficiencia { get; set; }
        public string nome_orientador { get; set; }
        public string titulo { get; set; }
        public Nullable<System.DateTime> data_defesa { get; set; }
        public string nome_do_curso { get; set; }
        public string reduzido { get; set; }
    }
}
